#!/bin/sh
#sudo apt install python3-pip
#sudo apt-get install net-tools
#sudo apt-get install vim
#sudo apt-get install mysql-server

#indicator
#sudo apt-get install curl gir1.2-appindicator3-0.1 python3-psutil

sudo apt-get install build-essential cmake cmake-data autoconf automake pkg-config libtool libzip-dev libxml2-dev
sudo apt-get install libsigc++-2.0-dev libglade2-dev libgtkmm-2.4-dev libglu1-mesa-dev libgl1-mesa-glx
sudo apt-get install mesa-common-dev libmysqlclient-dev libmysqlcppconn-dev uuid-dev libpixman-1-dev libpcre3-dev
sudo apt-get install libgnome2-dev libgnome-keyring-dev libgtk2.0-dev libpango1.0-dev libcairo2-dev python-dev
sudo apt-get install libboost-dev libctemplate-dev mysql-client python-pysqlite2 libsqlite3-dev
sudo apt-get install swig libvsqlitepp-dev libgdal-dev libproj0
sudo apt-get install gtk+-3.0
sudo apt-get install libgtkmm-3.0-dev
sudo add-apt-repository ppa:webupd8team/java
sudo apt install oracle-java8-set-default

#mono
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list

sudo apt update
sudo add-apt-repository ppa:webupd8team/atom

#atualizar ppas
sudo apt-get --allow-releaseinfo-change update

#touchpad mouse
sudo add-apt-repository ppa:atareao/atareao
sudo apt-get install touchpad-indicator
